### ISSUE TITLE
Copy icon is missing a tool tip

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal-frontend#150]
On this page:  http://cbioportal-frontend-demo.herokuapp.com/?cancer_study_id=lgg_ucsf_2014&case_id=P04

the copy icon is missing a tool tip.

**Comment by onursumer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tooltip is broken for the copy button (TableHeaderControls)](https://trello.com/c/KMUYCFdx/89-tooltip-is-broken-for-the-copy-button-tableheadercontrols)

**Comment by onursumer** [comment]
@alisman This is because of the recently added component `ClipboardButton`. Seems like directly wrapping this component with a `Tooltip` doesn't work. We need to find a workaround.

Wrapping the `ClipboardButton` inside a `<span>` element restores the tooltip, but it distorts the button group. Another alternative is to add the tooltip to the image icon but that doesn't look that good either...

**Comment by alisman** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/161

**Comment by alisman** [comment]
@onursumer you were right about problem.  only way to fix this was to use clipboard.js directly  :(
