### ISSUE TITLE
Hypermutated Sample Fails

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal-frontend#163]
In the new front-end:  http://cbioportal-frontend-demo.herokuapp.com/?cancer_study_id=ucec_tcga&case_id=TCGA-AP-A0LM-01

this hyper-mutated sample fails to load.

Not sure what the problem is, but looks like one of the APIs is failing:

![screenshot_1533](https://cloud.githubusercontent.com/assets/1009066/22695636/63c0e660-ed19-11e6-9c77-f90297140bda.png)

![screenshot_1534](https://cloud.githubusercontent.com/assets/1009066/22695650/72b04850-ed19-11e6-9fc8-234e9b275f61.png)

Not entirely sure who can fix this, but assigning to Ersin for now.

**Comment by ersinciftci** [comment]
It's related to https://trello.com/c/7SjkKJxc/81-8-mutation-table-retrieve-mrna-expr-data-lazily ticket, once it's implemented, this one will be solved.

**Comment by ersinciftci** [comment]
@ecerami sorry, the reason your URL fails is cancer_study_id is wrong, it should be `ucec_tcga_pub`, http://cbioportal-frontend-demo.herokuapp.com/?cancer_study_id=ucec_tcga_pub&case_id=TCGA-AP-A0LM, this will show the mutation table but won't load mrna-percentiles because of `Mutation Table --> retrieve mRNA Expr data lazily`.

**Comment by ersinciftci** [comment]
@ecerami actually, I just realized both `ucec_tcga_pub` and `ucec_tcga` are valid studies, so the problem was not cancer_study_id, it was the case_id, it needs to be Patient ID, but in your URL it was Sample ID. Sorry for the confusion. If it's sample id, it's sample_id in URL, if it's patient id, it's case_id.
