### ISSUE TITLE
Should we use PureRenderMixin?

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal-frontend#53]
Instead of writing shouldComponentUpdate everywhere. I saw a few places where the function is incorrect, using a Mixin might prevent that.

https://facebook.github.io/react/docs/pure-render-mixin.html

**Comment by adufilie** [comment]
We could use this:
https://github.com/adufilie/WeaveJS/blob/namespaces/srcts/weavejs/ui/SmartComponent.tsx#L36

That mixin only does shallow compare, and Facebook does not recommend mixins anyway:
https://github.com/facebook/react/blob/c78464f8ea9a5b00ec80252d20a71a1482210e57/docs/_posts/2016-07-13-mixins-considered-harmful.md#why-mixins-are-broken

**Comment by alisman** [comment]
Keep in mind we are using Immutable.js for this specific reason--to allow for shallow comparison in shouldComponentUpdate (or some helper like Pure Render mixin) rather than paying the cost of deep comparison with _.isEqual.     Lets discuss whether to use pure render mixin or a superclass that provides it (a la Smart Component).  I think FB's case against mixins is more about people creating lots of custom mixins of their own to avoid inheritance.   PureRenderMixin strikes me as a great case for a mixin.  Almost like an annotation.

**Comment by adufilie** [comment]
If you want to use their shallowCompare then you can do this: https://github.com/facebook/react/blob/c78464f/docs/_posts/2016-07-13-mixins-considered-harmful.md#solution

I don't think _.isEqual is a high cost to pay.  If shallow compare in shouldComponentUpdate is the only reason to use immutable.js, then I would argue against it for simplicity.  React does tell you when you've mutated state incorrectly at runtime.

**Comment by alisman** [comment]
The question of whether _.isEqual is a high cost to pay is a question of the size of data the data we are diffing and the frequency we need to make the comparison.  It struck me that our application, a data intensive application which already has front end performance issues, is a likely candidate for immutability.   Perhaps we should do some benchmarking to see if it is really necessary.

**Comment by adufilie** [comment]
Just had a thought on this. You had said that the data would not be changing often and when it does, it would be a complete replacement rather than modified in place. If that is the case, then the deep equality test is guaranteed to be fast because it short circuits when it sees two references to the same object.
