### ISSUE TITLE
3D view not working 

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal-frontend#714]
3D view is currently not working on cbioportal.org or any other installation outside mskcc.

This is probably due to the hard-coded URL here:
https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/shared/api/urls.ts#L80

@jjgao is this URL equivalent to the genomenexus solution?

**Comment by onursumer** [comment]
@pieterlukasse This URL (https://cbioportal.mskcc.org/pdb-annotation) is not equivalent to the Genome Nexus solution. It is publicly available and provides additional information which we don't host at  Genome Nexus yet.

The API that is actually causing this problem is `g2s.genomenexus.org`. Seems like we always get an empty result set. This must be related to some recent updates. We are trying to figure out the problem.

**Comment by jjgao** [comment]
@onursumer let's find a way to host extra info in genome nexus or g2s so that we can retire pdb-anntoation.war. https://github.com/cBioPortal/cbioportal-frontend/issues/721
