### ISSUE TITLE
React JS table for the core-mutation columns for mock json data in the cbioportal-frontend repo

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal-frontend#93]

**Comment by onursumer** [comment]
@alisman @inodb was this the react table you were talking about: https://github.com/tannerlinsley/react-table

**Comment by alisman** [comment]
Hi Onur, 
No, we settled on http://glittershark.github.io/reactable/
Unfortunately, it was missing a key feature, so we forked it.  You can use it as follows:

import {Table as DataTable} from "reactableMSK";

**Comment by onursumer** [comment]
@alisman @inodb  here is my generic data table proposal:

- Initialize the table with a certain set of columns (example: initialize with core mutation data)
- Render the initial data.
- Fetch the data for additional columns on demand -- Additional data can be retrieved either from the server side, or via a cross-domain API call.
- Once the data is ready for a specific column, render the actual column content.

Let's say we want to render cosmic data on demand as an additional column, and assume that we have defined `CosmicCell` as: `columnFormatters={ { 'cosmic': CosmicCell } }`.

If we want to fetch the cosmic data in the `CosmicCell` component, we need the core mutation data accessible to that component in order to query the cosmic API endpoint.

Alternatively, we can keep `CosmicCell` simple. For example, if there is no data for cosmic column it renders a placeholder image, and when the data becomes available it replaces it with the actual content. In that case we need to deal with data fetching on a higher level.

Which one do you think is a better way to handle the additional data sources?

In any case, we need to provide a mechanism to add a custom column by defining a data fetcher component/function, and a renderer component/function. The data fetcher should be able to use the existing initial data for API queries.
